/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsIpAddressRouteImport } from './routes/what-is-ip-address'
import { Route as VpnExplainedRouteImport } from './routes/vpn-explained'
import { Route as VpnCheckerRouteImport } from './routes/vpn-checker'
import { Route as SpeedTestRouteImport } from './routes/speed-test'
import { Route as OnlinePrivacyGuideRouteImport } from './routes/online-privacy-guide'
import { Route as LocationGeneratorRouteImport } from './routes/location-generator'
import { Route as InternetSpeedGuideRouteImport } from './routes/internet-speed-guide'
import { Route as DnsLeakExplainedRouteImport } from './routes/dns-leak-explained'
import { Route as DnsLeakRouteImport } from './routes/dns-leak'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIpRouteImport } from './routes/api.ip'

const WhatIsIpAddressRoute = WhatIsIpAddressRouteImport.update({
  id: '/what-is-ip-address',
  path: '/what-is-ip-address',
  getParentRoute: () => rootRouteImport,
} as any)
const VpnExplainedRoute = VpnExplainedRouteImport.update({
  id: '/vpn-explained',
  path: '/vpn-explained',
  getParentRoute: () => rootRouteImport,
} as any)
const VpnCheckerRoute = VpnCheckerRouteImport.update({
  id: '/vpn-checker',
  path: '/vpn-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedTestRoute = SpeedTestRouteImport.update({
  id: '/speed-test',
  path: '/speed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinePrivacyGuideRoute = OnlinePrivacyGuideRouteImport.update({
  id: '/online-privacy-guide',
  path: '/online-privacy-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationGeneratorRoute = LocationGeneratorRouteImport.update({
  id: '/location-generator',
  path: '/location-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const InternetSpeedGuideRoute = InternetSpeedGuideRouteImport.update({
  id: '/internet-speed-guide',
  path: '/internet-speed-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsLeakExplainedRoute = DnsLeakExplainedRouteImport.update({
  id: '/dns-leak-explained',
  path: '/dns-leak-explained',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsLeakRoute = DnsLeakRouteImport.update({
  id: '/dns-leak',
  path: '/dns-leak',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpRoute = ApiIpRouteImport.update({
  id: '/api/ip',
  path: '/api/ip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns-leak': typeof DnsLeakRoute
  '/dns-leak-explained': typeof DnsLeakExplainedRoute
  '/internet-speed-guide': typeof InternetSpeedGuideRoute
  '/location-generator': typeof LocationGeneratorRoute
  '/online-privacy-guide': typeof OnlinePrivacyGuideRoute
  '/speed-test': typeof SpeedTestRoute
  '/vpn-checker': typeof VpnCheckerRoute
  '/vpn-explained': typeof VpnExplainedRoute
  '/what-is-ip-address': typeof WhatIsIpAddressRoute
  '/api/ip': typeof ApiIpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns-leak': typeof DnsLeakRoute
  '/dns-leak-explained': typeof DnsLeakExplainedRoute
  '/internet-speed-guide': typeof InternetSpeedGuideRoute
  '/location-generator': typeof LocationGeneratorRoute
  '/online-privacy-guide': typeof OnlinePrivacyGuideRoute
  '/speed-test': typeof SpeedTestRoute
  '/vpn-checker': typeof VpnCheckerRoute
  '/vpn-explained': typeof VpnExplainedRoute
  '/what-is-ip-address': typeof WhatIsIpAddressRoute
  '/api/ip': typeof ApiIpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns-leak': typeof DnsLeakRoute
  '/dns-leak-explained': typeof DnsLeakExplainedRoute
  '/internet-speed-guide': typeof InternetSpeedGuideRoute
  '/location-generator': typeof LocationGeneratorRoute
  '/online-privacy-guide': typeof OnlinePrivacyGuideRoute
  '/speed-test': typeof SpeedTestRoute
  '/vpn-checker': typeof VpnCheckerRoute
  '/vpn-explained': typeof VpnExplainedRoute
  '/what-is-ip-address': typeof WhatIsIpAddressRoute
  '/api/ip': typeof ApiIpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dns-leak'
    | '/dns-leak-explained'
    | '/internet-speed-guide'
    | '/location-generator'
    | '/online-privacy-guide'
    | '/speed-test'
    | '/vpn-checker'
    | '/vpn-explained'
    | '/what-is-ip-address'
    | '/api/ip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dns-leak'
    | '/dns-leak-explained'
    | '/internet-speed-guide'
    | '/location-generator'
    | '/online-privacy-guide'
    | '/speed-test'
    | '/vpn-checker'
    | '/vpn-explained'
    | '/what-is-ip-address'
    | '/api/ip'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dns-leak'
    | '/dns-leak-explained'
    | '/internet-speed-guide'
    | '/location-generator'
    | '/online-privacy-guide'
    | '/speed-test'
    | '/vpn-checker'
    | '/vpn-explained'
    | '/what-is-ip-address'
    | '/api/ip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DnsLeakRoute: typeof DnsLeakRoute
  DnsLeakExplainedRoute: typeof DnsLeakExplainedRoute
  InternetSpeedGuideRoute: typeof InternetSpeedGuideRoute
  LocationGeneratorRoute: typeof LocationGeneratorRoute
  OnlinePrivacyGuideRoute: typeof OnlinePrivacyGuideRoute
  SpeedTestRoute: typeof SpeedTestRoute
  VpnCheckerRoute: typeof VpnCheckerRoute
  VpnExplainedRoute: typeof VpnExplainedRoute
  WhatIsIpAddressRoute: typeof WhatIsIpAddressRoute
  ApiIpRoute: typeof ApiIpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-ip-address': {
      id: '/what-is-ip-address'
      path: '/what-is-ip-address'
      fullPath: '/what-is-ip-address'
      preLoaderRoute: typeof WhatIsIpAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpn-explained': {
      id: '/vpn-explained'
      path: '/vpn-explained'
      fullPath: '/vpn-explained'
      preLoaderRoute: typeof VpnExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpn-checker': {
      id: '/vpn-checker'
      path: '/vpn-checker'
      fullPath: '/vpn-checker'
      preLoaderRoute: typeof VpnCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-test': {
      id: '/speed-test'
      path: '/speed-test'
      fullPath: '/speed-test'
      preLoaderRoute: typeof SpeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-privacy-guide': {
      id: '/online-privacy-guide'
      path: '/online-privacy-guide'
      fullPath: '/online-privacy-guide'
      preLoaderRoute: typeof OnlinePrivacyGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-generator': {
      id: '/location-generator'
      path: '/location-generator'
      fullPath: '/location-generator'
      preLoaderRoute: typeof LocationGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet-speed-guide': {
      id: '/internet-speed-guide'
      path: '/internet-speed-guide'
      fullPath: '/internet-speed-guide'
      preLoaderRoute: typeof InternetSpeedGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-leak-explained': {
      id: '/dns-leak-explained'
      path: '/dns-leak-explained'
      fullPath: '/dns-leak-explained'
      preLoaderRoute: typeof DnsLeakExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-leak': {
      id: '/dns-leak'
      path: '/dns-leak'
      fullPath: '/dns-leak'
      preLoaderRoute: typeof DnsLeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ip': {
      id: '/api/ip'
      path: '/api/ip'
      fullPath: '/api/ip'
      preLoaderRoute: typeof ApiIpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DnsLeakRoute: DnsLeakRoute,
  DnsLeakExplainedRoute: DnsLeakExplainedRoute,
  InternetSpeedGuideRoute: InternetSpeedGuideRoute,
  LocationGeneratorRoute: LocationGeneratorRoute,
  OnlinePrivacyGuideRoute: OnlinePrivacyGuideRoute,
  SpeedTestRoute: SpeedTestRoute,
  VpnCheckerRoute: VpnCheckerRoute,
  VpnExplainedRoute: VpnExplainedRoute,
  WhatIsIpAddressRoute: WhatIsIpAddressRoute,
  ApiIpRoute: ApiIpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
